### ISSUE TITLE
下划线显示错误

### ISSUE THREAD

**Issue by PZZZB** [cantry100/YLYRichText#2]
当字号变大，且文子够长时，下划线左右两端会有一些渐变，看上去很奇怪。如图
![image](https://user-images.githubusercontent.com/7671107/49328915-02385f00-f5b3-11e8-9ba1-fa4362a0bbf7.png)

测试过，当字号在20+时，比较明显。

**Comment by PuzzledBoy** [comment]
应该是和Unity版本有关，我是2017.4.16f1，根据编译提示，对YlyRictText类中的color和OnDestroy 加上 Override 之后就正常了。

**Comment by PZZZB** [comment]
自己更改了下划线的uv坐标处理方式，进行了修复，代码在Pull requests中。
